### ISSUE TITLE
Search/filter the fields in the current editor

### ISSUE THREAD

**Issue by Helias** [azerothcore/Keira3#794]
Add a way to search a specific field in a editor.

**Comment by Kitzunu** [comment]
Tried implementing https://github.com/TheoXiong/electron-find but running into this
![image](https://user-images.githubusercontent.com/24550914/87804589-5fe6f100-c854-11ea-8d9c-3fc162ec7d4b.png)

**Comment by Kitzunu** [comment]
>>> ReferenceError: document is not defined
    at E:\Keira3\node_modules\electron-find\src\utils.js:5:3
    at Object.<anonymous> (E:\Keira3\node_modules\electron-find\src\utils.js:20:3)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Function.Module._load (electron/js2c/asar.js:748:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (E:\Keira3\node_modules\electron-find\src\find.js:2:19)

**Comment by Kitzunu** [comment]
Thinking about it, its probably me doing something wrong since im new and not too familiar with Node TS and Electron
